#!/bin/sh
prompt_timestamp() {
    date +%s%N
}

timer_start() {
    timer=${timer:-$(prompt_timestamp)}
}

prompt_generator() {

	local timestring
	local delta_us=$(( ($(prompt_timestamp) - timer) / 1000 ))
	local ms=$(((delta_us / 1000) % 1000))
	local s=$(((delta_us / 1000000) % 1000))
	# local s=$((delta_us / 1000000))
	# local s=$(((delta_us / 1000000) % 60))

	timestring="$(( s >= 1 ? s : ms ))"

	timestring="$(printf '%03d' $timestring)"

    [ $s -ge 1 ] && \
        PS1=" \[\e[35m\]$timestring \[\e[34m\]\W\[\e[m\] > " \
    || \
		PS1=" \[\e[36m\]$timestring \[\e[34m\]\W\[\e[m\] > "

	unset timer
}

PROMPT_COMMAND=prompt_generator

trap 'timer_start' DEBUG

# OLD 
#  \[\e[34m\]\W\[\e[m\] > 
